name: Test and PR

on:
  push:
    branches:
      - Unicorn

jobs:
  test_and_pr:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"

      - name: Get list of tested commits
        run: |
          $tested_commits = git log --grep='TESTED' --pretty=format:"%h" | Out-String
          $tested_commits = $tested_commits.Trim()
          Write-Host "::set-output name=tested_commits::$tested_commits"

      - name: Create PR if tested commits exist
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          base: Int
          branch: Unicorn
          title: "Merge tested commits to Int"
          body: "This PR includes commits with the 'TESTED' label from the 'Unicorn' branch."

          # Check if there are tested commits before creating a PR
          condition: ${{ steps.create_pr.outputs.created == 'true' }}
